tasks:
  - name: standard
    init: |
      nvm install v12
      nvm use v12 
      npm install
    command: npm run start
  - name: my test
    command: date
vscode:
  extensions:
    - https://github.com/jimmygc/linenote-codelens/releases/download/1.0.1/linenote-codelens-1.0.1.vsix