tasks:
  - name: standard
    init: npm install
    command: npm run start
  - name: my test
    command: ls
vscode:
  extensions:
    - https://github.com/jimmygc/linenote-codelens/releases/download/1.0.1/linenote-codelens-1.0.1.vsix